### PR TITLE
Refresh toggle button

### LINKED ISSUE #47: Add a overall auto-fresh toggle
Add a toggle button to top right corner of the app to enable/disable auto refreshing.

- Toggle text = `Enable Auto Refresh` when disabled and `Disable Auto Refresh` when enabled.

### PR DESCRIPTION
**Pull request by johachi**
This should close #47 
I also change a state change in `ProjectDetails.js` to use the previous state. (Row 59-63).
I also ran the linter before writing my code.

Expected behaviour
When turning off:
1. Pressing the switch will disable auto refresh for all projects.
1. Individual Auto Refresh Settings for each project will be turned off.

When turning on:
1. Pressing the switch will enable possibility for auto refresh for all projects.
1. Individual Auto Refresh Settings will be set to ON/OFF depending on if they where ON/OFF before global auto refresh was turned off.

### CODE REVIEW

**Comment by haroon-sheikh** [comment]
@johachi it looks like when entering value, unless you press enter the changes dont take affect. - should set the value once set
also pressing enter when no value, it continuously fetches the APIs - should just set to default timeout. i.e. 30 secs

**Comment by johachi** [comment]
> @johachi The auto refresh is broken, its not fetching when setting to enabled.

Checking now!

**Comment by johachi** [comment]
Fixed! Everything should now work as expected.

**Comment by haroon-sheikh** [comment]
Thanks @johachi.

**Pull request merged**
