### PR TITLE
Updated Card view for project row

### PR DESCRIPTION
**Pull request by sachinttn9663**
screencapture-localhost-3000-2020-10-05-21_22_13
screencapture-localhost-3000-2020-10-05-21_21_58

### CODE REVIEW

**Comment by sachinttn9663** [comment]
@haroon-sheikh PFA

**Comment by haroon-sheikh** [comment]
@sachinttn9663 It looks great but the only problem now is when you have  multiple projects, it repeats the headings each time.

**Comment by sachinttn9663** [comment]
> @sachinttn9663 It looks great but the only problem now is when you have multiple projects, it repeats the headings each time.

Ok, but i think its ok because when project get extended with it commits then other cards will have clear headings in their card.
but no problem , Just confirm should i remove headings?

**Comment by sachinttn9663** [comment]
@haroon-sheikh 

screencapture-localhost-3000-2020-10-06-17_32_16

**Comment by sachinttn9663** [comment]
@haroon-sheikh Please review and mentioned if further you need any change

**Comment by sachinttn9663** [comment]
@haroon-sheikh Thanks, 
Feel free to ask  if you need any other UI related changes

**Comment by haroon-sheikh** [comment]
Thanks for looking into these @sachinttn9663. 

I've now created a separate issue #68 for improvements.

**Comment by sachinttn9663** [comment]
> Thanks for looking into these @sachinttn9663.
> 
> I've now created a separate issue #68 for improvements.

Assign it to me will happy to contribute

**Pull request merged**
