### PR TITLE
Updating Card view styles

### PR DESCRIPTION
**Pull request by sachinttn9663**
@haroon-sheikh PFA

screencapture-localhost-3000-2020-10-05-08_34_15

### CODE REVIEW

**Comment by sachinttn9663** [comment]
@haroon-sheikh , Please review and provide feedback if any

**Review by haroon-sheikh — CHANGES_REQUESTED** [review]
@sachinttn9663 This looks good and achieves the look of the cards. But i was looking for more like converting each project in the list to a floating card view. Similar to https://github.com/Paraboly/react-native-card 

Would you be able to have a look at that?

**Comment by sachinttn9663** [comment]
@haroon-sheikh Updated screenshot attached

**Comment by haroon-sheikh** [comment]
@sachinttn9663 You've added a cardview list to commit history.. But we need to also add that for the projectlist.

**Comment by sachinttn9663** [comment]
I think you should merge it, will create another PR fot that

**Review by haroon-sheikh — APPROVED** [review]

**Comment by haroon-sheikh** [comment]
Your changes should now be live at https://commit-status.herokuapp.com/

**Pull request merged**
