### PR TITLE
Ability to add and remove projects from the list

### LINKED ISSUE #10: Ability to add/remove projects from the UI
Currently, the app shows a list of projects based on flat json file.

This is to allow adding and removing of projects using the UI.

### PR DESCRIPTION
**Pull request by Prateek93a**
I have implemented the required feature. In the search box, one has to only write the repo name, for eg- 
env-config, the repo will be displayed and user may add it to list. If anything else is required, do let me know.

Fixes #10

### CODE REVIEW

**Comment by haroon-sheikh** [comment]
@Prateek93a It looks like its only searching for projects within the `sitture` group.. We should adding of projects with group name... So when searching `golang/go`, it should straighaway add the project if it exists.

- Change the search button to add button
- Allow adding of any project.. should check if the project exists and then add automatically.
- Change the "remove" text to "x" icon

**Comment by Prateek93a** [comment]
Ok

**Comment by Prateek93a** [comment]
For other repos like golang/go, I am recieving status of 'pending'.

**Comment by haroon-sheikh** [comment]
That's because they dont have any commit statuses, in that case `pending` is expected.
Can you resolve the conflicts, and make the remaining changes please?

**Comment by haroon-sheikh** [comment]
@Prateek93a Going to merge this in but the projects list resets on refresh. I've created a separate issue to tackle this https://github.com/sitture/commit-status/issues/16

**Pull request merged**
